// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nyayabharat.Infrastructure.Data;

#nullable disable

namespace Nyayabharat.Infrastructure.Migrations
{
    [DbContext(typeof(NyayabharatDbContext))]
    [Migration("20260301033958_SyncAfterManualChanges")]
    partial class SyncAfterManualChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Act", b =>
                {
                    b.Property<int>("ActId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActId"));

                    b.Property<int?>("ActCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ActName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnactedYear")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActId");

                    b.HasIndex("ActCategoryId");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.ActCategory", b =>
                {
                    b.Property<int>("ActCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActCategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ActCategoryId");

                    b.ToTable("ActCategories", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Amendment", b =>
                {
                    b.Property<int>("AmendmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmendmentId"));

                    b.Property<int>("ActId")
                        .HasColumnType("int");

                    b.Property<int>("AmendmentYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("AmendmentId");

                    b.ToTable("Amendments");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.AppealRight", b =>
                {
                    b.Property<int>("AppealRightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealRightId"));

                    b.Property<string>("AppealCourt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("TimeLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppealRightId");

                    b.ToTable("AppealRights");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<int>("ActId")
                        .HasColumnType("int");

                    b.Property<string>("ChapterNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChapterId");

                    b.HasIndex("ActId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Clause", b =>
                {
                    b.Property<int>("ClauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClauseId"));

                    b.Property<string>("ClauseLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClauseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubSectionId")
                        .HasColumnType("int");

                    b.HasKey("ClauseId");

                    b.HasIndex("SubSectionId");

                    b.ToTable("Clauses");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Concept", b =>
                {
                    b.Property<int>("ConceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConceptId"));

                    b.Property<string>("ConceptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimpleDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConceptId");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.ConceptSection", b =>
                {
                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("ConceptId", "SectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("ConceptSectionMap", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Explanation", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("LegalExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimpleExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionId");

                    b.ToTable("Explanations");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Judgment", b =>
                {
                    b.Property<int>("JudgmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JudgmentId"));

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourtLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JudgmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JudgmentId");

                    b.ToTable("Judgments");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("AllowedUserType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExplanationSectionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExplanationSectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AttemptId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.QuizAttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptAnswerId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("int");

                    b.HasKey("AttemptAnswerId");

                    b.ToTable("QuizAttemptAnswers");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.QuizAttemptQuestion", b =>
                {
                    b.Property<int>("AttemptQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptQuestionId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AttemptQuestionId");

                    b.ToTable("QuizAttemptQuestions");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionAmendment", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("AmendmentId")
                        .HasColumnType("int");

                    b.HasKey("SectionId", "AmendmentId");

                    b.HasIndex("AmendmentId");

                    b.ToTable("SectionAmendmentMap", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("ContentId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionContents");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionJudgmentMap", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("JudgmentId")
                        .HasColumnType("int");

                    b.HasKey("SectionId", "JudgmentId");

                    b.HasIndex("JudgmentId");

                    b.ToTable("SectionJudgmentMap", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionParallel", b =>
                {
                    b.Property<int>("SectionParallelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionParallelId"));

                    b.Property<string>("MappingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewActId")
                        .HasColumnType("int");

                    b.Property<string>("NewSectionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OldActId")
                        .HasColumnType("int");

                    b.Property<int>("OldSectionId")
                        .HasColumnType("int");

                    b.HasKey("SectionParallelId");

                    b.ToTable("SectionParallelMap");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Situation", b =>
                {
                    b.Property<int>("SituationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SituationId");

                    b.ToTable("Situations");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SituationConcept", b =>
                {
                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.HasKey("SituationId", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("SituationConceptMap", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SituationGuidance", b =>
                {
                    b.Property<int>("GuidanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuidanceId"));

                    b.Property<string>("GuidanceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("GuidanceId");

                    b.HasIndex("SituationId");

                    b.ToTable("SituationGuidance");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SituationSection", b =>
                {
                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("int");

                    b.HasKey("SituationId", "SectionNumber");

                    b.HasIndex("SectionNumber");

                    b.ToTable("SituationSectionMap", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SubSection", b =>
                {
                    b.Property<int>("SubSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubSectionId"));

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("SubSectionLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubSectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("SubSections");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Translation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FieldName");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TranslatedText");

                    b.HasKey("TranslationId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Translations", (string)null);
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.UserBookmark", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "SectionId");

                    b.ToTable("UserBookmarks");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.UserProgress", b =>
                {
                    b.Property<int>("UserProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProgressId"));

                    b.Property<int?>("ConceptId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAttemptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserProgressId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Act", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.ActCategory", "ActCategory")
                        .WithMany("Acts")
                        .HasForeignKey("ActCategoryId");

                    b.Navigation("ActCategory");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Act", null)
                        .WithMany("Chapters")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Clause", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.SubSection", null)
                        .WithMany("Clauses")
                        .HasForeignKey("SubSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.ConceptSection", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Concept", "Concept")
                        .WithMany("ConceptSections")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyayabharat.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Explanation", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Section", "Section")
                        .WithOne("Explanation")
                        .HasForeignKey("Nyayabharat.Domain.Entities.Explanation", "SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Option", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Question", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Explanation", "Explanation")
                        .WithMany()
                        .HasForeignKey("ExplanationSectionId");

                    b.HasOne("Nyayabharat.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId");

                    b.Navigation("Explanation");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Section", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Act", "Act")
                        .WithMany()
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyayabharat.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId");

                    b.Navigation("Act");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionAmendment", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Amendment", "Amendment")
                        .WithMany()
                        .HasForeignKey("AmendmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyayabharat.Domain.Entities.Section", "Section")
                        .WithMany("SectionAmendments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amendment");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionContent", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyayabharat.Domain.Entities.Section", "Section")
                        .WithMany("SectionContents")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SectionJudgmentMap", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Judgment", "Judgment")
                        .WithMany()
                        .HasForeignKey("JudgmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judgment");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SituationConcept", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Concept", "Concept")
                        .WithMany("SituationConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyayabharat.Domain.Entities.Situation", "Situation")
                        .WithMany("SituationConcepts")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SituationGuidance", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Situation", "Situation")
                        .WithMany()
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SituationSection", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Section", "Section")
                        .WithMany("SituationSections")
                        .HasForeignKey("SectionNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nyayabharat.Domain.Entities.Situation", "Situation")
                        .WithMany("SituationSections")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SubSection", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Section", null)
                        .WithMany("SubSections")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Translation", b =>
                {
                    b.HasOne("Nyayabharat.Domain.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Act", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.ActCategory", b =>
                {
                    b.Navigation("Acts");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Concept", b =>
                {
                    b.Navigation("ConceptSections");

                    b.Navigation("SituationConcepts");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Section", b =>
                {
                    b.Navigation("Explanation");

                    b.Navigation("SectionAmendments");

                    b.Navigation("SectionContents");

                    b.Navigation("SituationSections");

                    b.Navigation("SubSections");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.Situation", b =>
                {
                    b.Navigation("SituationConcepts");

                    b.Navigation("SituationSections");
                });

            modelBuilder.Entity("Nyayabharat.Domain.Entities.SubSection", b =>
                {
                    b.Navigation("Clauses");
                });
#pragma warning restore 612, 618
        }
    }
}
